// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY0xfQCH9rX-1_14-nrW8ycTtmvDdYSWg',
    appId: '1:266056983192:web:16f19d8cbf76a667d7e6ed',
    messagingSenderId: '266056983192',
    projectId: 'iot-esp-fa661',
    authDomain: 'iot-esp-fa661.firebaseapp.com',
    databaseURL: 'https://iot-esp-fa661-default-rtdb.firebaseio.com',
    storageBucket: 'iot-esp-fa661.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmdAcJxPoydSi-t6rFgDN7LzNhhWCTnJc',
    appId: '1:266056983192:android:3e2d4fa88faa8bb1d7e6ed',
    messagingSenderId: '266056983192',
    projectId: 'iot-esp-fa661',
    databaseURL: 'https://iot-esp-fa661-default-rtdb.firebaseio.com',
    storageBucket: 'iot-esp-fa661.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbcA4pnzhw7soDDRLwQw3fjDIkzQcbk0g',
    appId: '1:266056983192:ios:3239b8ef63328ec8d7e6ed',
    messagingSenderId: '266056983192',
    projectId: 'iot-esp-fa661',
    databaseURL: 'https://iot-esp-fa661-default-rtdb.firebaseio.com',
    storageBucket: 'iot-esp-fa661.appspot.com',
    iosClientId: '266056983192-3h40ooggr81bmr8la9697gfcpigv81cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.automata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbcA4pnzhw7soDDRLwQw3fjDIkzQcbk0g',
    appId: '1:266056983192:ios:3239b8ef63328ec8d7e6ed',
    messagingSenderId: '266056983192',
    projectId: 'iot-esp-fa661',
    databaseURL: 'https://iot-esp-fa661-default-rtdb.firebaseio.com',
    storageBucket: 'iot-esp-fa661.appspot.com',
    iosClientId: '266056983192-3h40ooggr81bmr8la9697gfcpigv81cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.automata',
  );
}
